import Phaser from "phaser";
import { ELEMENT_ORDER, ELEMENTS } from "../game/elements";
import battleData from "../content/battle-01.json";
import type { FindWordBattle } from "../content/types";

/** Loads audio, generates the particle texture, then hands off to StartScene. */
export class BootScene extends Phaser.Scene {
  constructor() {
    super("Boot");
  }

  preload(): void {
    // Kenney.nl CC0 sounds, converted to mp3 for cross-browser support
    // (iPad Safari can't play ogg). See public/audio/CREDITS.md.
    this.load.audio("impact", "audio/impact.mp3");
    this.load.audio("wrong", "audio/wrong.mp3");
    this.load.audio("tap", "audio/tap.mp3");
    this.load.audio("win", "audio/win.mp3");
    for (const el of ELEMENT_ORDER) {
      this.load.audio(ELEMENTS[el].sound, `audio/${ELEMENTS[el].sound}.mp3`);
    }

    // Kenney CC0 sprite art (UI Pack: Adventure + Monster Builder Pack).
    this.load.image("ui-button", "assets/ui/button_brown.png");
    this.load.image("ui-panel", "assets/ui/panel_brown.png");
    this.load.image("m-body", "assets/monster/body_greenD.png");
    this.load.image("m-eye", "assets/monster/eye_cute_light.png");
    this.load.image("m-mouth", "assets/monster/mouthE.png");
    this.load.image("m-arm", "assets/monster/arm_greenC.png");
    this.load.image("m-leg", "assets/monster/leg_greenB.png");
    this.load.image("player-idle", "assets/player/idle.png");
    this.load.image("player-attack", "assets/player/attack.png");
    this.load.image("player-cheer", "assets/player/cheer.png");

    // Male-voice word reading: one baked clip per prompt (Windows "David",
    // generated by tools/gen-voice.ps1). Plus Kenney CC0 male callouts.
    const battle = battleData as FindWordBattle;
    battle.prompts.forEach((_, i) => this.load.audio(`voice-p${i}`, `audio/voice/p${i}.mp3`));
    this.load.audio("vo-correct", "audio/voice/vo_correct.mp3");
    this.load.audio("vo-win", "audio/voice/vo_win.mp3");
  }

  create(): void {
    // A soft white dot used for all particle effects (tinted per element).
    const g = this.add.graphics();
    g.fillStyle(0xffffff, 1);
    g.fillCircle(8, 8, 8);
    g.generateTexture("spark", 16, 16);
    g.destroy();

    this.scene.start("Start");
  }
}
