import Phaser from "phaser";
import { ELEMENT_ORDER, ELEMENTS } from "../game/elements";
import battleData from "../content/battle-01.json";
import type { FindWordBattle } from "../content/types";
import { ALL_ENEMIES } from "../content/enemies";
import { ALL_ROOMS, TRANSITION_FILE, TRANSITION_KEY } from "../content/rooms";

/** Loads audio, generates the particle texture, then hands off to StartScene. */
export class BootScene extends Phaser.Scene {
  constructor() {
    super("Boot");
  }

  preload(): void {
    // Kenney.nl CC0 sounds, converted to mp3 for cross-browser support
    // (iPad Safari can't play ogg). See public/audio/CREDITS.md.
    this.load.audio("impact", "audio/impact.mp3");
    this.load.audio("wrong", "audio/wrong.mp3");
    this.load.audio("tap", "audio/tap.mp3");
    this.load.audio("win", "audio/win.mp3");
    for (const el of ELEMENT_ORDER) {
      this.load.audio(ELEMENTS[el].sound, `audio/${ELEMENTS[el].sound}.mp3`);
    }

    // Kenney CC0 UI sprite art (UI Pack: Adventure).
    this.load.image("ui-button", "assets/ui/button_brown.png");
    this.load.image("ui-panel", "assets/ui/panel_brown.png");

    // Original pixel-art characters, authored in tools/gen-sprites.py: the young
    // "word mage" hero (three poses) and the whole enemy roster (one texture per
    // creature, so any level's enemy is ready without a mid-run load).
    this.load.image("player-idle", "assets/player/idle.png");
    this.load.image("player-attack", "assets/player/attack.png");
    this.load.image("player-cheer", "assets/player/cheer.png");
    for (const enemy of ALL_ENEMIES) {
      this.load.image(enemy.key, enemy.file);
    }

    // Castle room backgrounds (one per level theme) + the transition screen —
    // original pixel art from tools/gen-backgrounds.py.
    for (const room of ALL_ROOMS) {
      this.load.image(room.key, room.file);
    }
    this.load.image(TRANSITION_KEY, TRANSITION_FILE);

    // Male-voice word reading: one baked clip per prompt for level 1 (Windows
    // "David", generated by tools/gen-voice.ps1). Plus the Kenney CC0 win
    // callout. (Per-answer praise is now visual — see BattleScene.celebrate —
    // so the spoken "Correct!" is no longer loaded.)
    const battle = battleData as FindWordBattle;
    battle.prompts.forEach((_, i) => this.load.audio(`voice-p${i}`, `audio/voice/p${i}.mp3`));
    this.load.audio("vo-win", "audio/voice/vo_win.mp3");
  }

  create(): void {
    // A soft white dot used for all particle effects (tinted per element).
    const g = this.add.graphics();
    g.fillStyle(0xffffff, 1);
    g.fillCircle(8, 8, 8);
    g.generateTexture("spark", 16, 16);
    g.destroy();

    this.scene.start("Start");
  }
}
